# Generated by Django 4.1.7 on 2023-04-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPPMarketPlace', '0003_product_description_product_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
